# Generated by Django 5.2.3 on 2025-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='A short title for the image (optional)', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('description', models.TextField(blank=True, help_text='A brief description of the image (optional)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this image on the homepage or elsewhere.')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
