# Generated by Django 5.2.3 on 2025-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_tag_galleryimage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this tag from the gallery filters.'),
        ),
    ]
