# Generated by Django 5.2.3 on 2025-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryimage_contributor_galleryimage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_guest_accessible',
            field=models.BooleanField(default=False, help_text='Check to make this tag available for guests to select when uploading photos.'),
        ),
    ]
