# Generated by Django 5.2.3 on 2025-06-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attending', models.BooleanField(default=True, verbose_name='Will you be attending?')),
                ('number_of_guests', models.PositiveIntegerField(default=1, help_text='Including yourself, how many people will be in your party?', verbose_name='Number in Party')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or messages for the couple.', null=True, verbose_name='Additional Notes')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guest Name')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Optional: For meal planning (e.g., child meal).', null=True, verbose_name='Guest Age')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='e.g., Vegetarian, Gluten-free, Nut allergy', null=True, verbose_name='Dietary Restrictions')),
                ('favorite_song', models.CharField(blank=True, help_text='What song would get this guest on the dance floor?', max_length=100, null=True, verbose_name='Favorite Song')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.rsvp')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['name'],
            },
        ),
    ]
