# Generated by Django 5.2.3 on 2025-11-16 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_alter_rsvp_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(blank=True, help_text='Your email address.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvp_submission', to=settings.AUTH_USER_MODEL),
        ),
    ]
